version: '3.8'

services:
  my-app:
    image: docker-all-systems-image  # 使用你刚刚构建的镜像
    container_name: my-tomcat
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql  # 数据持久化
      - ./sql-scripts:/docker-entrypoint-initdb.d/  # 自动导入 SQL 文件

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "8081:80"
    depends_on:
      - mysql
